extends: default

rules:
  indentation:
    spaces: 2
    indent-sequences: whatever
    check-multi-line-strings: false

  line-length:
    max: 150
    level: warning

  empty-lines:
    max: 2

  document-start: disable

  truthy:
    allowed-values: ['true', 'false']
    check-keys: false
