{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "sematext-agent.fullname" . }}-vector
  labels:
    app: {{ template "sematext-agent.name" . }}-vector
    chart: {{ template "sematext-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - nodes
  - namespaces
  verbs:
  - watch
  - list
{{- end }}
