apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sematext-agent.fullname" . }}-agent
  labels:
    app: {{ template "sematext-agent.name" . }}-agent
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  REGION: {{ .Values.region | quote }}
  {{- range $key, $val := .Values.agent.config }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  {{- if .Values.serverBaseUrl }}
  SERVER_BASE_URL: {{ default "" .Values.serverBaseUrl | quote }}
  {{- end }}
  {{- if .Values.eventsReceiverUrl }}
  EVENTS_RECEIVER_URL: {{ default "" .Values.eventsReceiverUrl | quote }}
  {{- end }}
  {{- if .Values.logsReceiverUrl }}
  LOGS_RECEIVER_URL: {{ default "" .Values.logsReceiverUrl | quote }}
  {{- end }}
  API_SERVER_PORT: "{{ .Values.agent.service.port }}"
  {{- if .Values.commandServerUrl }}
  COMMAND_SERVER_URL: {{ default "" .Values.commandServerUrl | quote }}
  {{- end }}
  {{- if .Values.otel.enabled }}
  OTEL_ENABLED: "true"
  {{- if .Values.otel.metrics.enabled }}
  OTEL_METRICS_ENABLED: "true"
  OTEL_METRICS_RECEIVER_GRPC_ENDPOINT: {{ .Values.otel.metrics.receiver.grpc.endpoint | quote }}
  OTEL_METRICS_RECEIVER_HTTP_ENDPOINT: {{ .Values.otel.metrics.receiver.http.endpoint | quote }}
  {{- else }}
  OTEL_METRICS_ENABLED: "false"
  {{- end }}
  {{- if .Values.otel.logs.enabled }}
  OTEL_LOGS_ENABLED: "true"
  OTEL_LOGS_RECEIVER_GRPC_ENDPOINT: {{ .Values.otel.logs.receiver.grpc.endpoint | quote }}
  OTEL_LOGS_RECEIVER_HTTP_ENDPOINT: {{ .Values.otel.logs.receiver.http.endpoint | quote }}
  {{- else }}
  OTEL_LOGS_ENABLED: "false"
  {{- end }}
  {{- if .Values.otel.traces.enabled }}
  OTEL_TRACES_ENABLED: "true"
  OTEL_TRACES_RECEIVER_GRPC_ENDPOINT: {{ .Values.otel.traces.receiver.grpc.endpoint | quote }}
  OTEL_TRACES_RECEIVER_HTTP_ENDPOINT: {{ .Values.otel.traces.receiver.http.endpoint | quote }}
  {{- else }}
  OTEL_TRACES_ENABLED: "false"
  {{- end }}
  {{- else }}
  OTEL_ENABLED: "false"
  {{- end }}
