{{- if .Values.priorityClass }}
apiVersion: scheduling.k8s.io/v1
kind: PriorityClass
metadata:
  name: {{ .Values.priorityClass.name }}
  labels:
    app: {{ template "sematext-agent.name" . }}
    chart: {{ template "sematext-agent.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
value: {{ .Values.priorityClass.value }}
preemptionPolicy: PreemptLowerPriority
globalDefault: false
description: "Sematext priority: used for Sematext Agent and Vector logshipper"
{{- end }}