{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sematext-agent.fullname" . }}
  labels:
    app: {{ template "sematext-agent.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
data:
  infra-token: {{ default "" .Values.infraToken | b64enc | quote }}
  logs-token: {{ default "" .Values.logsToken | b64enc | quote }}
  {{- range $groupName, $groupConfig := .Values.otel.token-groups }}
  {{- if index $groupConfig "monitoring-token" }}
  otel-{{ $groupName }}-monitoring-token: {{ index $groupConfig "monitoring-token" | b64enc | quote }}
  {{- end }}
  {{- if index $groupConfig "logs-token" }}
  otel-{{ $groupName }}-logs-token: {{ index $groupConfig "logs-token" | b64enc | quote }}
  {{- end }}
  {{- if index $groupConfig "traces-token" }}
  otel-{{ $groupName }}-traces-token: {{ index $groupConfig "traces-token" | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
