{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sematext-agent.fullname" . }}
  labels:
    app: {{ template "sematext-agent.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
data:
  infra-token: {{ default "" .Values.infraToken | b64enc | quote }}
  logs-token: {{ default "" .Values.logsToken | b64enc | quote }}
{{- end }}
