{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "sematext-agent.fullname" . }}
  labels:
    app: {{ template "sematext-agent.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
type: Opaque
data:
  infra-token: {{ default "" .Values.infraToken | b64enc | quote }}
  logs-token: {{ default "" .Values.logsToken | b64enc | quote }}
  traces-token: {{ default "" .Values.tracesToken | b64enc | quote }}
  {{- range $groupName, $groupConfig := (index .Values.otel "token-groups") }}
  {{- if index $groupConfig "monitoring-token" }}
  {{ printf "otel-%s-monitoring-token" $groupName | quote }}: {{ index $groupConfig "monitoring-token" | b64enc | quote }}
  {{- end }}
  {{- if index $groupConfig "logs-token" }}
  {{ printf "otel-%s-logs-token" $groupName | quote }}: {{ index $groupConfig "logs-token" | b64enc | quote }}
  {{- end }}
  {{- if index $groupConfig "traces-token" }}
  {{ printf "otel-%s-traces-token" $groupName | quote }}: {{ index $groupConfig "traces-token" | b64enc | quote }}
  {{- end }}
  {{- end }}
{{- end }}
