# Install using a pre-existing Kubernetes secret
clusterName: "ci-test-cluster"

existingSecret:
  name: "sematext-tokens"
  hasInfraToken: true
  hasLogsToken: true
  hasTracesToken: false

rbac:
  create: true

serviceAccount:
  create: true

hostNetwork: false
